### ISSUE TITLE
KafkaLoad

### ISSUE THREAD

**Issue by inamg** [tripl-ai/arc-kafka-pipeline-plugin#4]
I am using kafkaload to push data to kafka which is running in container locally. Stage is successful but I dont see any messages in kafka..

`{
  "type": "KafkaLoad",
  "name": "write customer to kafka",
  "environments": [
    "production",
    "test"
  ],
  "inputView": "customer_json",
  "bootstrapServers": "localhost:9092",
  "topic": "customer-updated"
}`

**Comment by seddonm1** [comment]
hi,
firstly, sorry it should work.

can you please answer:

1. what version you are using (it was updated yesterday)
2. streaming vs batch
3. can you confirm customer_json has records (you can turn on persist=true to easily get row count)

then we can start debugging

**Comment by inamg** [comment]
hey @seddonm1 thanks for the reply.
customer_json  does have records.
I am using arc-jupyter_1.3.0_scala_2.11_1.0.0

**Comment by seddonm1** [comment]
Can you try arc-jupyter_1.4.0_scala_2.11_hadoop_2.7.7_1.0.0?

**Comment by inamg** [comment]
pull access denied for triplai/arc-jupyter_1.4.0_scala_2.11_hadoop_2.7.7_1.0.0

**Comment by seddonm1** [comment]
triplai/arc-jupyter:arc-jupyter_1.4.0_scala_2.11_hadoop_2.7.7_1.0.0

**Comment by seddonm1** [comment]
also can you try using an ip address instead of 'localhost'

**Comment by inamg** [comment]
doesnt work even with ip

**Comment by seddonm1** [comment]
what does the schema of customer_json look like? just a single column of string JSON?

**Comment by inamg** [comment]
yep just a single column of json..i tried with very simple schema with only one property

**Comment by seddonm1** [comment]
could you try with just a basic string value just any value?
